import { Nunito } from "next/font/google";
import clsx from "clsx";
import Providers from "@/components/providers";
import "./globals.css";

const nunito = Nunito({
  weight: ["300", "400", "600", "700", "800", "900"],
  variable: "--font-nunito",
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={clsx(nunito.variable, "font-nunito")}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
