import { Nunito } from "next/font/google";
import clsx from "clsx";
import "./globals.css";

const nunitoSans = Nunito({
  variable: "--font-nunito",
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={clsx(nunitoSans.variable, "font-nunito")}>
      <body>{children}</body>
    </html>
  );
}
